# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "attachments", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "caption",      :string
    t.column "url",          :string
    t.column "position",     :integer
    t.column "author",       :string
    t.column "type",         :string
    t.column "user_id",      :integer
    t.column "event_id",     :integer
    t.column "report_id",    :integer
  end

  create_table "calendars", :force => true do |t|
    t.column "name",              :string
    t.column "short_description", :text
    t.column "user_id",           :integer
  end

  create_table "events", :force => true do |t|
    t.column "name",                :string
    t.column "short_description",   :text
    t.column "description",         :text
    t.column "calendar_id",         :integer
    t.column "location",            :text
    t.column "city",                :string
    t.column "state",               :string
    t.column "postal_code",         :string
    t.column "host_id",             :integer
    t.column "start",               :datetime
    t.column "end",                 :datetime
    t.column "service_foreign_key", :string
    t.column "latitude",            :float
    t.column "longitude",           :float
  end

  create_table "reports", :force => true do |t|
    t.column "event_id", :integer
    t.column "user_id",  :integer
    t.column "text",     :text
    t.column "position", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "title", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "user_id", :integer
  end

  create_table "rsvps", :id => false, :force => true do |t|
    t.column "event_id", :integer
    t.column "user_id",  :integer
    t.column "comment",  :text
    t.column "guests",   :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "phone",                     :string
    t.column "street",                    :string
    t.column "street_2",                  :string
    t.column "city",                      :string
    t.column "state",                     :string
    t.column "postal_code",               :string
  end

  create_table "zip_codes", :force => true do |t|
    t.column "zip",       :string
    t.column "city",      :string
    t.column "state",     :string, :limit => 2
    t.column "latitude",  :string
    t.column "longitude", :string
    t.column "zip_class", :string
  end

end
